// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/redux-immutable-state-invariant/redux-immutable-state-invariant.d.ts
declare module "redux-immutable-state-invariant" {
    type isImmutableDefault = (value: any) => boolean;
    type immutableStateInvariantMiddlewareInterface = (isImmutable?: isImmutableDefault) => Redux.Middleware;
    let immutableStateInvariantMiddleware: immutableStateInvariantMiddlewareInterface;
    export = immutableStateInvariantMiddleware;
}
