// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/acdc2d397ce53133deda238a55b4148c6cfdc901/redux-mock-store/redux-mock-store.d.ts
declare module 'redux-mock-store' {
    import * as Redux from 'redux'

    function createMockStore<T>(middlewares?:Redux.Middleware[]):mockStore<T>

    type mockStore<T> = (state?:T) => IStore<T>;

    type IStore<T> = {
        dispatch(action: any):any
        getState():T
        getActions():Object[]
        clearActions():void
        subscribe(listener: Function):Function
    }

    export default createMockStore
}
